version: '3'

networks:
  system:
  
volumes:
  mariadb:

services:
  bunny:
    build:
      context: '.'
      dockerfile: "bunny.Dockerfile"
    ports:
      - "15678:15672"
    networks:
      - system
    hostname: bunny1

  maria:
    build:
      context: "."
      dockerfile: "mariadb.Dockerfile"
    networks:
      - system
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mariadb:/var/lib/mysql

  py-c:
    build:
      context: "."
      dockerfile: "py-c.Dockerfile"
    networks:
      - system
    depends_on: 
      - bunny
      - maria

  py-p:
    build:
      context: "."
      dockerfile: "py-p.Dockerfile"
    networks:
      - system
    depends_on: 
      - maria
      - bunny