version: '3'

networks:
  compose-net:

volumes:
  mariadb:

services:
  bunny:
    build:
      context: '.'
      dockerfile: "bunny.Dockerfile"
    ports:
      - "15673:15672"
    networks:
      - compose-net
    hostname: bunny1
  
  maria:
    build:
      context: '.'
      dockerfile: "mariadb.Dockerfile"
    networks:
      - compose-net
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mariadb:/var/lib/mysql
  
  py-c:
    build:
      context: '.'
      dockerfile: "py-c.Dockerfile"
    networks:
      - compose-net
    depends_on:
      - bunny
      - maria
  
  py-p:
    build:
      context: '.'
      dockerfile: "py-p.Dockerfile"
    networks:
      - compose-net
    depends_on:
      - maria
      - bunny