version: '3'

networks:
  system:

services:
  bunny:
    build:
      context: '.'
      dockerfile: "bunny.Dockerfile"
    ports:
      - "15678:15672"
    networks:
      - system
    hostname: bunny1


  database:
    build:
      context: "."
      dockerfile: "mariadb.Dockerfile"
    networks:
      - system
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  consume:
    build:
      context: "."
      dockerfile: "py-c.Dockerfile"
    networks:
      - system
    depends_on: 
      - bunny
      - database

  produce:
    build:
      context: "."
      dockerfile: "py-p.Dockerfile"
    networks:
      - system
    depends_on: 
      - database
      - bunny